# Generated by Django 4.0.4 on 2022-11-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_vendor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='status',
            new_name='is_active',
        ),
    ]
