# Generated by Django 4.0.2 on 2022-11-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_customer_payment_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment',
            name='account',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
