# Generated by Django 4.0.2 on 2022-11-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_vendor_payment_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_payment',
            name='running_bal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_payment',
            name='running_bal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
