# Generated by Django 4.0.2 on 2022-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_expense_banking_running_bal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_banking',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='expense_banking',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='vendor_payment',
            name='ref_no',
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
