# Generated by Django 4.0.2 on 2022-11-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_expense_banking_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_banking',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor_payment',
            name='ref_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
