# Generated by Django 4.0.2 on 2022-11-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_customer_payment_bnkid_expense_banking_bnkid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_payment',
            old_name='bnkid',
            new_name='accounts1id',
        ),
        migrations.RenameField(
            model_name='expense_banking',
            old_name='bnkid',
            new_name='accounts1id',
        ),
        migrations.RenameField(
            model_name='vendor_payment',
            old_name='bnkid',
            new_name='accounts1id',
        ),
    ]
