# Generated by Django 4.0.2 on 2022-11-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_bnkid_customer_payment_accounts1id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_payment',
            name='accounts1id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1'),
        ),
        migrations.AlterField(
            model_name='expense_banking',
            name='accounts1id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1'),
        ),
        migrations.AlterField(
            model_name='vendor_payment',
            name='accounts1id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1'),
        ),
    ]
